apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  labels:
    app: cloud-app
spec:
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
